name: Build TrackMe
on: [push, workflow_dispatch]

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Récupérer le code
        uses: actions/checkout@v4

      - name: ☕ Configurer Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: 🛠️ Ajouter le wrapper Gradle
        run: |
          chmod +x gradlew
          sed -i 's|https://services.gradle.org|https://mirrors.cloud.tencent.com/gradle|g' gradle/wrapper/gradle-wrapper.properties

      - name: 🔨 Compiler l'APK
        run: ./gradlew assembleDebug --no-daemon

      - name: 📦 Récupérer l'APK
        uses: actions/upload-artifact@v4
        with:
          name: TrackMe-APK
          path: app/build/outputs/apk/debug/app-debug.apk
